# appspec 파일은 배포시, codedeploy가 참조하는 파일
# 해당 파일에 명시된 대로 deploy가 진행되기 때문에 appspec 파일이 존재하지 않으면 에러 발생
version: 0.0
os: linux

files:
  # root에서 애플리케이션을 가져와 /home/ec2-user/tars 디렉토리로 복사
  - source:  /
    destination: /home/ec2-user/tars
    # 같은 파일이 존재한다면 덮어쓰기
    overwrite: yes

# 같은 파일이 존재한다면 덮어쓰기
file_exists_behavior: OVERWRITE

# root 디렉토리의 그룹과 소유자를 ec2-user로 설정
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  # 서버가 실행중이라면 강제 종료
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user